language: node_js
node_js:
  - 14.16.0
before_install:
  - npm install -g npm
script:
  - npm install
  - npm run build:ssr
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: JURkFevf7Ghg3OEX89kh/AFnVsj//c9gy2DeXwWw37ruIQBP3nzrOD73PRErqK6BKrL3myIsgqAxLR80jazTKVLj1IAn+c+SyYobExqayaERHsoKLk12uR0KH2mmcYd1txzHuuiY3JhMAts9Pk4FmST6MuyWW7Hqv495xx25j2XLtRLW48kpJyE9AN3v8RE65qrtq69EgblzJME1ipy2EXKQhdH5W41eB2L7p64sw4BTGnwUutfJ7rMwIqJnTxgSkweuYn3zSGZjpoYNImaJfD16OzZ2k8rLzleNaxg5iaC7ruFBL7t3FCR3s1+ro5K3FRUnPWl32pZvoz6hOtfUCERUZvUicPZcCA+tFK2CEW0CMfU/JbvczmHDRDl0vTEs4dhu27omLrdf8n0NsixzGOGr7BnOc/gl4IRr2RA6Rsk8wSWLt6/ZpWvgSeIcKY3E1ICWpNg3H4Al6+zd2o5rxU9dPJiEntNFG7JFbwgOFMAfyDyiH1xdN56SRsJPL4zpjF0+RdmPLWdnAf8NNQm5yWsmegg5g3duq/kh1rpmc6SL33XKP92Qmq2Umd5jwMKOlyVQBAOEFBOXYoLa3mTvORTVPh1PdaIXUmHhD2iVXI5CICS34fAZueFHInzM/0byHGMgY+uK48oAz7pSwbVc70j2Y/1MzLQbZeF2IrA5zpM=
  app: ps-xt-coding
  on:
    branch: main
