language: node_js
node_js:
  - "15.11.0"

script:
  - ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local-dir: ./dist/
  on:
    branch: main
